spring:
  application:
    name: nce-cert
    version: 0.0.1
ncp:
  api:
    accessKey: rp08euZ0GBkAMbxdkFmq
    secretKey: WilmZ071vjAX9Ryy0iRD8COoswaQwsVpp3v5F5e9
    host: https://certificatemanager.apigw.ntruss.com